[package]
name = "starfield-render"
version = "0.1.1"
authors = ["Mitchell Bruckner <mbruckner807@gmail.com>"]

[[bin]]
name = "stars"

[[bin]]
name = "gradient"

[[bin]]
name = "perspective"

[dependencies]
nalgebra="0.8.2"
rand="0.3.*"
